name: test changelog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: "./.github/workflows/release_changelog.json"
          commitMode: "true"
          fromTag: "0.14.0"
          toTag: "0.15.0"
      - name: "debug output"
        run: echo "Changelog >>> ${{steps.build_changelog.outputs.changelog}}"
