name: coverage
on:
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup dependencies
        run: yarn
      - name: Build advanced slides
        run: npm run build
      - name: Test advanced slides
        run: npm test
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
