name: release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup dependencies
        run: yarn
      - name: Build advanced slides
        run: npm run build
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'obsidian-advanced-slides.zip'
          directory: 'test-vault/.obsidian/plugins/obsidian-advanced-slides/'
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          artifacts: "test-vault/.obsidian/plugins/obsidian-advanced-slides/obsidian-advanced-slides.zip, test-vault/.obsidian/plugins/obsidian-advanced-slides/main.js, test-vault/.obsidian/plugins/obsidian-advanced-slides/manifest.json, test-vault/.obsidian/plugins/obsidian-advanced-slides/styles.css"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          
